# Start with the official Go image
FROM golang:1.20.5-alpine AS build

# Set the working directory inside the container
WORKDIR /source

# Copy the source code to the container
COPY . .

# Build the Go application
RUN go build /source/app/authentication/main.go -o authentication

# Final stage
FROM scratch

# Copy the executable from the build stage
COPY --from=build /app/authentication /authentication

# Set the entrypoint script
COPY start.sh /start.sh
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]
